import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { mkdir, readFile, symlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { packageToSkillId } from "@world2agent/sdk";
import { pathExists, removePath } from "./manifest.js";
import type { World2AgentPaths } from "./types.js";

export interface InstalledPackageInfo {
  packageJsonPath: string;
  packageRoot: string;
  packageJson: Record<string, unknown>;
}

export function pluginPackageRoot(): string {
  return fileURLToPath(new URL("../", import.meta.url));
}

export async function resolveInstalledPackage(
  pkg: string,
): Promise<InstalledPackageInfo | null> {
  const require = createRequire(import.meta.url);
  try {
    const entryPath = require.resolve(pkg, {
      paths: [pluginPackageRoot()],
    });
    const packageJsonPath = await findNearestPackageJson(dirname(entryPath));
    const raw = JSON.parse(await readFile(packageJsonPath, "utf8")) as Record<string, unknown>;
    return {
      packageJsonPath,
      packageRoot: dirname(packageJsonPath),
      packageJson: raw,
    };
  } catch {
    return null;
  }
}

export async function ensurePackageInstalled(
  pkg: string,
): Promise<InstalledPackageInfo> {
  const existing = await resolveInstalledPackage(pkg);
  if (existing) return existing;

  const localRepo = await findLocalSensorRepo(pkg);
  if (localRepo) {
    await linkLocalPackage(pkg, localRepo);
    const linked = await resolveInstalledPackage(pkg);
    if (linked) return linked;
  }

  await runCommand("npm", ["install", "--no-save", pkg], {
    cwd: pluginPackageRoot(),
  });
  const installed = await resolveInstalledPackage(pkg);
  if (!installed) {
    throw new Error(`Failed to resolve installed package ${pkg}`);
  }
  return installed;
}

export async function maybeUninstallPackage(
  pkg: string,
): Promise<void> {
  try {
    await runCommand("npm", ["uninstall", "--no-save", pkg], {
      cwd: pluginPackageRoot(),
    });
  } catch {
    // best effort
  }
}

export async function writeGeneratedSkill(
  paths: World2AgentPaths,
  pkg: string,
  installed: InstalledPackageInfo,
): Promise<string> {
  const skillId = packageToSkillId(pkg);
  const sourceType = String(
    (installed.packageJson.w2a as Record<string, unknown> | undefined)?.source_type ?? pkg,
  );
  const signals = (
    (installed.packageJson.w2a as Record<string, unknown> | undefined)?.signals as
      | string[]
      | undefined
  )?.join(", ");

  const skillDir = join(paths.openclawSkillsDir, skillId);
  await mkdir(skillDir, { recursive: true });
  const skillMd = [
    "---",
    `name: ${skillId}`,
    `description: Handle World2Agent signals from ${pkg}.`,
    "user-invocable: false",
    "---",
    "",
    `# ${skillId}`,
    "",
    `Handle W2A signals from \`${pkg}\` (source type: \`${sourceType}\`).`,
    "",
    "## Inputs",
    "- The prompt body contains markdown context plus a fenced JSON copy of the full `signal` object.",
    signals ? `- Common signal types: ${signals}` : "- Inspect `signal.event.type` for the exact event kind.",
    "",
    "## Behavior",
    "- Parse the JSON when you need structured fields.",
    "- If the signal is irrelevant or obviously low-value, skip silently.",
    "- If it is actionable, reply briefly with the key fact, why it matters, and any obvious next step.",
    "",
    "## Notes",
    "- This skill was generated by @world2agent/openclaw-plugin because the sensor package does not ship a richer OpenClaw-specific handler yet.",
    "- If the dedicated World2Agent agent does not expose a skills allowlist, the plugin falls back to `Use skill: <id>` prompt routing.",
    "",
  ].join("\n");
  await writeFile(join(skillDir, "SKILL.md"), skillMd, "utf8");
  return skillId;
}

export async function loadConfigFile(
  configFile: string | undefined,
  installed: InstalledPackageInfo,
): Promise<Record<string, unknown>> {
  if (!configFile) {
    const setupPath = String(
      (installed.packageJson.w2a as Record<string, unknown> | undefined)?.setup ?? "SETUP.md",
    );
    throw new Error(
      `Interactive setup is not implemented; use --config-file <path>. Sensor guidance: ${join(
        installed.packageRoot,
        setupPath,
      )}`,
    );
  }

  const raw = JSON.parse(await readFile(configFile, "utf8")) as unknown;
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error(`Config file must contain a JSON object: ${configFile}`);
  }
  return raw as Record<string, unknown>;
}

export async function runCommand(
  command: string,
  args: string[],
  options: {
    cwd?: string;
    env?: NodeJS.ProcessEnv;
  } = {},
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      env: options.env ?? process.env,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolvePromise({ stdout, stderr });
        return;
      }
      reject(
        new Error(
          `${command} ${args.join(" ")} failed with code ${code}: ${
            stderr.trim() || stdout.trim()
          }`,
        ),
      );
    });
  });
}

async function findLocalSensorRepo(pkg: string): Promise<string | null> {
  if (!pkg.startsWith("@world2agent/sensor-")) return null;

  const slug = pkg.split("/").pop()?.replace(/^sensor-/, "");
  if (!slug) return null;

  const candidate = resolve(pluginPackageRoot(), "..", "..", "world2agent-sensors", slug);
  return (await pathExists(join(candidate, "package.json"))) ? candidate : null;
}

async function linkLocalPackage(pkg: string, sourceDir: string): Promise<void> {
  const scope = pkg.split("/")[0];
  const name = pkg.split("/")[1];
  if (!scope || !name) {
    throw new Error(`Invalid package name: ${pkg}`);
  }

  const target = join(pluginPackageRoot(), "node_modules", scope, name);
  await mkdir(dirname(target), { recursive: true });
  await removePath(target);
  await symlink(sourceDir, target, "dir");
}

async function findNearestPackageJson(startDir: string): Promise<string> {
  let current = startDir;
  for (;;) {
    const candidate = join(current, "package.json");
    if (await pathExists(candidate)) {
      return candidate;
    }
    const parent = dirname(current);
    if (parent === current) {
      throw new Error(`Could not find package.json above ${startDir}`);
    }
    current = parent;
  }
}

